import ToastProvider from "@/Providers/ToastProvider";
import "./globals.css";
import { Roboto } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import HeaderV2 from "@/Components/SharedUI/Navs/HeaderV2";

import NextAuthProvider from "@/Providers/Provider";
import SignalR from "@/Components/SignalR";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} m-4 mt-0`}>
        <NextAuthProvider>
          <ToastProvider>
            <HeaderV2 />
            {children}
            <SignalR />
          </ToastProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
